### PR TITLE
Render JSON Feed entries’ content with render_content

### PR DESCRIPTION
**Pull request by bdesham**
See #148.

This isn’t ready yet; I’m only opening a PR so that I can see the CI output.

### CODE REVIEW

**Comment by bdesham** [comment]
@snarfed I fixed about half of the tests by just updating them with the app’s new behavior. There are some awkward cases left, though. Consider this error from the test_jsonfeed_to_activity_note test:

```
- A note. link too
+ A note. link too<p><img src="http://example.com/blog-post-123/image"/></p>

Expected value:
{'author': {'displayName': 'Ryan Barrett',
            'image': [{'url': 'http://example.com/ryan/image'}]},
 'content': 'A note. link too',
 'id': 'tag:example.com,2011:blog-post-123',
 'image': [{'url': 'http://example.com/blog-post-123/image'}],
 'objectType': 'note',
 'published': '2012-02-22T20:26:41',
 'summary': 'too cool to summarize',
 'updated': '2013-10-25T10:31:30+00:00',
 'url': 'http://example.com/blog-post-123'}
Actual value:
{'author': {'displayName': 'Ryan Barrett',
            'image': [{'url': 'http://example.com/ryan/image'}]},
 'content': 'A note. link too<p><img '
            'src="http://example.com/blog-post-123/image"/></p>',
 'id': 'tag:example.com,2011:blog-post-123',
 'image': [{'url': 'http://example.com/blog-post-123/image'}],
 'objectType': 'note',
 'published': '2012-02-22T20:26:41',
 'summary': 'too cool to summarize',
 'updated': '2013-10-25T10:31:30+00:00',
 'url': 'http://example.com/blog-post-123'}
```

The Activity Streams object ends up with an `img` tag in the `content` field that is redundant with the `image` field.

In general, given that JSON Feed needs some information (like embedded image URLs) to be included inline in the HTML while other formats carry that information out-of-band, there is going to be awkwardness converting between different formats, and I think it would be get a lot of work to get a transformation like “convert from AS to JSON Feed and then back to AS” to be idempotent, even assuming that the input is in exactly the format that Granary would have emitted. How would you like me to handle this?

**Comment by snarfed** [comment]
hey ben, i'm glad you're getting back to this! thank you!

> I think it would be get a lot of work to get a transformation like “convert from AS to JSON Feed and then back to AS” to be idempotent

absolutely right, i agree. i don't actually expect all round trip conversions like that to be idempotent. most of the file sets in `testdata/` only have some formats (by extension), not all, and some have special extensions like eg `.as-from-feed.json`, which `test_testdata.py` special cases to test only a one way conversion. feel free to use that liberally, and/or rename existing files to it to prevent them from testing a round trip.

also, if the test data approach is just too awkward altogether for testing something specific, feel free to add code-based tests to `test_jsonfeed.py` instead, or in extreme cases, even move testdata files there. that should hopefully be unlikely though.

thanks again!

**Comment by bdesham** [comment]
This is ready to be reviewed! I changed the tests in a way that made sense to me, but let me know what you think.

**Comment by snarfed** [comment]
looks great. thank you again for sticking with this!

**Comment by snarfed** [comment]
deployed!

**Comment by bdesham** [comment]
Awesome! Glad I could help 😃

**Pull request merged**
