### PR TITLE
Get base object for Bluesky replies

### PR DESCRIPTION
**Pull request by JoelOtter**
As discussed in https://github.com/snarfed/bridgy/issues/1580#issuecomment-1925314697

### CODE REVIEW

**Comment by snarfed** [comment]
This looks fine to me, happy to merge it once there's a test or two! Have you tested it locally though? Does it work?

**Comment by JoelOtter** [comment]
Yep, working fine locally - will add some tests : )

**Comment by JoelOtter** [comment]
@snarfed this sufficient? I couldn't really think what to add in terms of edge cases etc

**Comment by snarfed** [comment]
Perfect, thank you! Merging and deploying now...

**Pull request merged**
