### PR TITLE
Delegate tweet truncation to brevity

### PR DESCRIPTION
**Pull request by kylewm**
- removes parentheses on the link if the tweet text is truncated.
- support different formatting of article titles "The Title: permalink"

Fixes https://github.com/snarfed/bridgy/issues/553

Tbh, I'm not terribly invested in this, but I thought I'd send it so you could see. 
Even though it removes more code than it adds to Granary proper, 
it does add another dependency, and only really improves edge cases

### CODE REVIEW

**Comment by kylewm** [comment]
oh also, I moved those unit tests (that weren't already duplicates) into brevity https://github.com/kylewm/brevity/blob/27cf1e31a539695d3ad9cffa69b5e221218fb700/tests/brevity_test.py#L81

**Comment by snarfed** [comment]
you're too modest...this removes a lot of code! i like it, i'm in if you are. lgtm!

**Comment by kylewm** [comment]
haha, well it certainly *moves* code. we're still responsible for it if it breaks.

**Comment by kylewm** [comment]
Merging this is harder than just reapplying the changes; going to close it and file a new PR

**Pull request closed without merging**
